## 可选 mode: "standalone" | "raft" | "chash"
mode = "raft"

## 本节点配置
[self]
id = "node1"
http_address = "127.0.0.1:8080"
grpc_address = "127.0.0.1:9000"
role = "control"    # 可选，在本节点下无意义
weight = 1          # 只在 chash 模式有意义

## 底层存储配置
[storage]
path = "./data/node1"

## Raft 模式集群配置
[raft]
election_timeout_ms = 150
heartbeat_interval_ms = 50
leader_id = ""  # 可留空；运行时由选举产生

[[raft.nodes]]
id = "node1"
http_address = "127.0.0.1:8080"
grpc_address = "127.0.0.1:9000"
role = "control"
weight = 1

[[raft.nodes]]
id = "node2"
http_address = "127.0.0.1:8081"
grpc_address = "127.0.0.1:9001"
role = "control"
weight = 1

[[raft.nodes]]
id = "node3"
http_address = "127.0.0.1:8082"
grpc_address = "127.0.0.1:9002"
role = "control"
weight = 1